version: "3.8"

name: dev-env-vscode-base

services:
  app:
    container_name: base_dev
    build:
      # dev tools can be installed thru features (in devcontainer.json).
      # For specific tools not availabel thru, update the docker file
      context: .
      dockerfile: dockerfile-vscode-base
    command: sleep infinity
    environment:
      - ENV_VAR1=blah                   # environment variables here
    env_file:
      - path: ./devcontainer.env    # Add all secrets here. This file is not part of git
        required: false
