# This image already consists git, zsh, Oh My Zsh!, 
# a non-root vscode user with sudo access, and a set of common dependencies for development.
FROM mcr.microsoft.com/devcontainers/typescript-node:22

# ARG DEBIAN_FRONTEND=noninteractive
# RUN apt update \
#    && apt install -y --no-install-recommends sudo \
#    && apt autoremove -y \
#    && rm -rf /var/lib/apt/lists/* \
#    && echo "node ALL=(ALL) NOPASSWD: ALL" >/etc/sudoers.d/node \
#    && chmod 0440 /etc/sudoers.d/node
